.TH COMMIT 7 "2024年7月" "バージョン 1.0" "コミットメッセージプレフィックスマニュアル"
.SH 名前
commit \- Gitコミットメッセージのプレフィックスガイドライン

.SH 概要
Gitコミットメッセージの先頭にプレフィックスを使用することで、変更の内容を明確に伝えることができます。以下は、一般的に使用されるプレフィックスとその説明のリストです。

.TP
.B fix
既存の機能のバグを修正する場合に使用します。

.TP
.B hotfix
緊急の変更を追加する場合に使用します。

.TP
.B add
新しいファイルや機能を追加する場合に使用します。

.TP
.B feat
新しい機能やファイルを追加する場合に使用します。

.TP
.B update
既存の機能に問題がないが、修正を加えたい場合に使用します。

.TP
.B change
仕様変更により、既存の機能に修正を加えた場合に使用します。

.TP
.B clean / refactor
コードをリファクタリングし、改善する場合に使用します。

.TP
.B improve
コードの改善をする場合に使用します。

.TP
.B disable
機能を一時的に無効にする場合に使用します。

.TP
.B remove / delete
ファイルや機能を削除する場合に使用します。

.TP
.B rename
ファイル名を変更する場合に使用します。

.TP
.B move
ファイルを移動する場合に使用します。

.TP
.B upgrade
バージョンをアップグレードする場合に使用します。

.TP
.B revert
以前のコミットに戻す場合に使用します。

.TP
.B docs
ドキュメントを修正する場合に使用します。

.TP
.B style
コーディングスタイルの修正をする場合に使用します。

.TP
.B perf
コードのパフォーマンスを改善する場合に使用します。

.TP
.B test
テストコードを修正する場合や、テストコードを追加する場合に使用します。

.TP
.B chore
ビルドツールやライブラリで自動生成されたものをコミットする場合や、上記のプレフィックスに当てはまらない修正をする場合に使用します。

.SH ファイル
このマニュアルページは、\fI/usr/local/share/man/man7/commit.7\fRに設置されています。

.SH 著者
Yuto Endo